version: '3.8'
services:
  redisdb:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - my-network
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - my-network
  node-app:
    image: registry.digitalocean.com/node-registry/node-application:latest
    ports:
    - 80:3000
    networks:
      - my-network
    depends_on:
      - redisdb
      - mongodb
networks:
  my-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local