name: ci

on:
  push:
    branches:
      - master
    tags:
      - "v*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: tadascesna/node-app
      # - name: Login to DockerHub
      #   # if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      - name: Build image
        run: docker build -t node-application .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: |
          docker tag node-application registry.digitalocean.com/node-registry/node-application:latest
          docker tag node-application registry.digitalocean.com/node-registry/node-application:v1.2
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/node-registry/node-application
